Fix method name error: use getSingularName() instead of getName()
- ModuleController: Changed entity.getName() to entity.getSingularName()
- modules.controller.js: Added singularName field to module mapping and updated Dashboard check
- modules.html: Updated all Dashboard checks to use singularName instead of name
- Fixes compilation error: 'The method getName() is undefined for the type ErpEntity'